[workspace]
resolver = "3"

members = [
    "watermelon-pdb",   # main utils
    "parser",           # parse pdb and create input file for watermelon.
    "rewriter",         # remap/rewrite old pdb
]
